version = 0.1

[default.deploy.parameters]
stack_name = "openinvoice-cleaning-lambda"
resolve_s3 = true
s3_prefix = "openinvoice-cleaning-lambda"
region = "ca-central-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "ca-central-1"
